CREATE TABLE IF NOT EXISTS "user" (
    user_id INTEGER PRIMARY KEY AUTOINCREMENT,
    emp_no TEXT NOT NULL UNIQUE,
    emp_name TEXT NOT NULL,
    emp_name_eng TEXT NOT NULL,
    password TEXT NOT NULL,
    email TEXT,
    org_id TEXT NOT NULL,
    title TEXT ,
    lang_cd TEXT NOT NULL,
    created_by TEXT ,
    creation_date TEXT DEFAULT CURRENT_TIMESTAMP,
    last_updated_by TEXT,
    last_updated_date TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "menu" (
    menu_id INTEGER PRIMARY KEY,
    menu_name TEXT,
    menu_name_eng TEXT,
    menu_desc TEXT,
    menu_level INTEGER,
    prnt_menu_id INTEGER,
    dspl_flag TEXT,
    use_flag TEXT,
    sort_order INTEGER,
    url TEXT,
    param1 TEXT,
    param2 TEXT,
    param3 TEXT,
    param4 TEXT,
    param5 TEXT,
    ab_auth_flag TEXT,
    c_auth_flag TEXT,
    e_auth_flag TEXT,
    f_auth_flag TEXT,
    attribute1 TEXT,
    attribute2 TEXT,
    attribute3 TEXT,
    attribute4 TEXT,
    attribute5 TEXT,
    attribute6 TEXT,
    attribute7 TEXT,
    attribute8 TEXT,
    attribute9 TEXT,
    attribute10 TEXT,
    creation_date TEXT DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT,
    last_update_date TEXT DEFAULT CURRENT_TIMESTAMP,
    last_updated_by TEXT
);

