package com.third.gen_office.mis.co.actuals.dto;

public record CoActualResponse(
    String acctCd,
    String acctName,
    Integer acctLevel,
    String parentCd,
    String drCr,
    String fiscalYr,
    String fiscalPrd,
    String orgCd,
    Double currActAmt,
    Double planAmt,
    Double prevActAmt,
    Double m01,
    Double m02,
    Double m03,
    Double m04,
    Double m05,
    Double m06,
    Double m07,
    Double m08,
    Double m09,
    Double m10,
    Double m11,
    Double m12,
    String lastUpdatedBy,
    String lastUpdatedDate
) {}
